In [30]:
import pandas as pd
import os

In [31]:
root = "./TNVD_All"
files_all = []

for path, subdirs, files in os.walk(root):
    for name in files:
        files_all.append(os.path.join(path, name))

print(files_all)

['./TNVD_All/Республика Башкоторстан/DATTSVT.csv', './TNVD_All/Республика Марий Эл/DATTSVT.csv', './TNVD_All/Севастополь/DATTSVT.csv', './TNVD_All/Волгоградская область/DATTSVT.csv', './TNVD_All/Республика Северная Осетия-Алания/DATTSVT.csv', './TNVD_All/Республика Алтай/DATTSVT.csv', './TNVD_All/Республика Ингушетия/DATTSVT.csv', './TNVD_All/Томская область/DATTSVT.csv', './TNVD_All/Пензенская область/DATTSVT.csv', './TNVD_All/Эвенкийский автономный окргу (Красноярский край)/DATTSVT.csv', './TNVD_All/Ульяновская область/DATTSVT.csv', './TNVD_All/Коми-Пермятский автономный округ (Пермский край)/DATTSVT.csv', './TNVD_All/Ненецкий автономный округ (Архангельская область)/DATTSVT.csv', './TNVD_All/Краснодарский край/DATTSVT.csv', './TNVD_All/Челябинская область/DATTSVT.csv', './TNVD_All/Астраханская область/DATTSVT.csv', './TNVD_All/Рязанская область/DATTSVT.csv', './TNVD_All/Кировская область/DATTSVT.csv', './TNVD_All/Псковская область/DATTSVT.csv', './TNVD_All/Республика Адыгея/DATTSVT.csv', './TNVD_All/Оренбургская область/DATTSVT.csv', './TNVD_All/Республика Карелия/DATTSVT.csv', './TNVD_All/Вологодская область/DATTSVT.csv', './TNVD_All/Ханты-Мансийский автономный округ (Тюменская область)/DATTSVT.csv', './TNVD_All/Сахалинская область/DATTSVT.csv', './TNVD_All/Агинский Бурятский автономный округ (Читинская область)/DATTSVT.csv', './TNVD_All/Санкт-Петербург/DATTSVT.csv', './TNVD_All/Калининградская область/DATTSVT.csv', './TNVD_All/Чувашская Республика/DATTSVT.csv', './TNVD_All/Новосибирская область/DATTSVT.csv', './TNVD_All/Брянская область/DATTSVT.csv', './TNVD_All/Амурская область/DATTSVT.csv', './TNVD_All/Республика Татарстан/DATTSVT.csv', './TNVD_All/Тверская область/DATTSVT.csv', './TNVD_All/Республика Калмыкия/DATTSVT.csv', './TNVD_All/Тульская область/DATTSVT.csv', './TNVD_All/Белгородская область/DATTSVT.csv', './TNVD_All/Чукотский автономный округ/DATTSVT.csv', './TNVD_All/Магаданская область/DATTSVT.csv', './TNVD_All/Республика Бурятия/DATTSVT.csv', './TNVD_All/Курская область/DATTSVT.csv', './TNVD_All/Республика Дагестан/DATTSVT.csv', './TNVD_All/Ямало-Ненецкий автономный округ (Тюменская область)/DATTSVT.csv', './TNVD_All/Чеченская Республика/DATTSVT.csv', './TNVD_All/Нижегородская область/DATTSVT.csv', './TNVD_All/Республика Тыва/DATTSVT.csv', './TNVD_All/Свердловская область/DATTSVT.csv', './TNVD_All/Орловская область/DATTSVT.csv', './TNVD_All/Архангельская область/DATTSVT.csv', './TNVD_All/Ярославская область/DATTSVT.csv', './TNVD_All/Иркутская область/DATTSVT.csv', './TNVD_All/Забайкальский край/DATTSVT.csv', './TNVD_All/Республика Мордовия/DATTSVT.csv', './TNVD_All/Омская область/DATTSVT.csv', './TNVD_All/Самарская область/DATTSVT.csv', './TNVD_All/Карачаево-Черкесская Республика/DATTSVT.csv', './TNVD_All/Еврейский автономный округ/DATTSVT.csv', './TNVD_All/Удмуртская Республика/DATTSVT.csv', './TNVD_All/Таймырский (Долгано-Ненецкий) автономный округ (Красноярский край)/DATTSVT.csv', './TNVD_All/Московская область/DATTSVT.csv', './TNVD_All/Тюменская область/DATTSVT.csv', './TNVD_All/Новгородская область/DATTSVT.csv', './TNVD_All/Пермский край/DATTSVT.csv', './TNVD_All/Владимирская область/DATTSVT.csv', './TNVD_All/Республика Крым/DATTSVT.csv', './TNVD_All/Ставропольский край/DATTSVT.csv', './TNVD_All/Кемеровская область/DATTSVT.csv', './TNVD_All/Смоленская область/DATTSVT.csv', './TNVD_All/Калужская область/DATTSVT.csv', './TNVD_All/Саратовская область/DATTSVT.csv', './TNVD_All/Курганская область/DATTSVT.csv', './TNVD_All/Корякский автономный округ (Камчатская область)/DATTSVT.csv', './TNVD_All/Хабаровский край/DATTSVT.csv', './TNVD_All/Приморский край/DATTSVT.csv', './TNVD_All/Алтайский край/DATTSVT.csv', './TNVD_All/Ростовская область/DATTSVT.csv', './TNVD_All/Липецкая область/DATTSVT.csv', './TNVD_All/Ивановская область/DATTSVT.csv', './TNVD_All/Воронежская область/DATTSVT.csv', './TNVD_All/Москва/DATTSVT.csv', './TNVD_All/Тамбовская область/DATTSVT.csv', './TNVD_All/Республика Хакасия/DATTSVT.csv', './TNVD_All/Республика Коми/DATTSVT.csv', './TNVD_All/Усть-Ордынский Бурятский автономный округ (Иркутская область)/DATTSVT.csv', './TNVD_All/Кабардино-Балкарская Республика/DATTSVT.csv', './TNVD_All/Ленинградская область/DATTSVT.csv', './TNVD_All/Красноярский край/DATTSVT.csv', './TNVD_All/Неизвестная административно-территориальная единица/DATTSVT.csv', './TNVD_All/Мурманская область/DATTSVT.csv', './TNVD_All/Камчатский край/DATTSVT.csv', './TNVD_All/Республика Саха (Якутия)/DATTSVT.csv', './TNVD_All/Костромская область/DATTSVT.csv']

In [32]:
df_list = []
df_all = []

headers = ['napr','period','tnved','Stoim']

for file in files_all:
#     print(file)
    df_list.append(pd.read_csv(file, sep = '\t',usecols=headers,low_memory=False))

df = pd.concat(df_list)

In [33]:
# df = pd.read_csv('TNVD_10dig/DATTSVT_Kurskaya.csv', sep = '\t')

In [34]:
df.head()

  napr   period       tnved   Stoim
0   ИМ  04/2021  3506100000    2475
1   ИМ  10/2021  3507909000    1188
2   ИМ  08/2021  3507909000     340
3   ЭК  04/2021  3808932700  268979
4   ЭК  04/2021  3707100000  412,45

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4913026 entries, 0 to 12413
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   napr    object
 1   period  object
 2   tnved   object
 3   Stoim   object
dtypes: object(4)
memory usage: 187.4+ MB

In [36]:
df['napr'] = df['napr'].astype(str)
df['period'] = pd.to_datetime(df['period'])
df['tnved'] = df['tnved'].astype(str)    # при необходимости, можно сделать int64

df['Stoim'] = df['Stoim'].astype(str)
df['Stoim'] = df['Stoim'].str.replace(',', ".").astype(float)

# df['Netto'] = df['Netto'].str.replace(',', ".").astype(float)
# df['Kol'] = df['Kol'].str.replace(',', ".").astype(float)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4913026 entries, 0 to 12413
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   napr    object
 1   period  datetime64[ns]
 2   tnved   object
 3   Stoim   float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 187.4+ MB

In [38]:
df_tnvd = df.groupby(['tnved', 'napr'], as_index= False).agg({'Stoim':'sum'})

In [39]:
df_tnvd.head()

        tnved napr         Stoim
0  0101210000   ИМ  4.378226e+06
1  0101210000   ЭК  7.614870e+05
2  0101291000   ЭК  1.695123e+05
3  0101299000   ИМ  2.774227e+06
4  0101299000   ЭК  1.737698e+06

In [40]:
df_tnvd = df_tnvd.sort_values(by='tnved', ascending=False)

In [41]:
df_tnvd.head(50)

            tnved napr         Stoim
19854  XXXXXXXXXX   ЭК  7.334388e+10
19853  XXXXXXXXXX   ИМ  1.386141e+10
19852  9706000000   ИМ  2.349157e+07
19851  9705000000   ЭК  2.683366e+06
19850  9705000000   ИМ  3.012531e+06
19849  9704000000   ЭК  8.405860e+03
19848  9704000000   ИМ  2.422170e+03
19846  9703000000   ИМ  1.279883e+06
19847  9703000000   ЭК  2.318645e+06
19845  9702000000   ИМ  2.914470e+04
19844  9701900000   ЭК  1.240715e+05
19843  9701900000   ИМ  7.502968e+04
19842  9701100000   ЭК  8.098574e+05
19841  9701100000   ИМ  4.719937e+06
19840  9620000009   ЭК  1.736408e+05
19839  9620000009   ИМ  3.851912e+06
19838  9620000008   ЭК  6.075220e+03
19837  9620000008   ИМ  5.340388e+05
19836  9620000007   ЭК  1.915757e+04
19835  9620000007   ИМ  4.553120e+05
19834  9620000006   ЭК  2.001098e+05
19833  9620000006   ИМ  4.012188e+06
19832  9620000005   ЭК  2.169275e+05
19831  9620000005   ИМ  5.558100e+06
19829  9620000004   ИМ  1.130678e+06
19830  9620000004   ЭК  8.242230e+03
19827  9620000003   ИМ  2.814589e+06
19828  9620000003   ЭК  6.898292e+04
19826  9620000002   ЭК  3.520700e+03
19825  9620000002   ИМ  9.824693e+04
19824  9620000001   ЭК  1.880138e+05
19823  9620000001   ИМ  5.522543e+06
19822  9619008909   ЭК  7.216590e+06
19821  9619008909   ИМ  6.580055e+07
19820  9619008901   ЭК  1.110712e+07
19819  9619008901   ИМ  3.672386e+06
19818  9619008109   ЭК  2.054684e+08
19817  9619008109   ИМ  2.111511e+08
19816  9619008101   ЭК  3.597834e+06
19815  9619008101   ИМ  3.158372e+06
19814  9619007909   ЭК  1.146053e+06
19813  9619007909   ИМ  4.237144e+06
19812  9619007901   ЭК  4.093027e+05
19811  9619007901   ИМ  1.000586e+06
19809  9619007509   ИМ  1.496140e+06
19810  9619007509   ЭК  1.808667e+04
19807  9619007501   ИМ  1.448974e+06
19808  9619007501   ЭК  1.165643e+05
19806  9619007109   ЭК  1.919042e+07
19805  9619007109   ИМ  1.404350e+08

In [42]:
df2 = df_tnvd.pivot(index='tnved', columns='napr', values='Stoim')

In [43]:
df2

napr                  ИМ            ЭК
tnved
0101210000  4.378226e+06  7.614870e+05
0101291000           NaN  1.695123e+05
0101299000  2.774227e+06  1.737698e+06
0101300000  2.670165e+04           NaN
0101900000           NaN  5.450600e+04
...                  ...           ...
9703000000  1.279883e+06  2.318645e+06
9704000000  2.422170e+03  8.405860e+03
9705000000  3.012531e+06  2.683366e+06
9706000000  2.349157e+07           NaN
XXXXXXXXXX  1.386141e+10  7.334388e+10

[10826 rows x 2 columns]

In [44]:
df2 = df2.reset_index()

In [45]:
df2.head(50)

napr       tnved            ИМ            ЭК
0     0101210000  4.378226e+06  7.614870e+05
1     0101291000           NaN  1.695123e+05
2     0101299000  2.774227e+06  1.737698e+06
3     0101300000  2.670165e+04           NaN
4     0101900000           NaN  5.450600e+04
5     0102211000  1.007747e+08  1.854020e+06
6     0102213000           NaN  2.037349e+05
7     0102219000  3.814162e+06  3.174175e+06
8     0102291000           NaN  6.554976e+04
9     0102292100           NaN  1.608432e+05
10    0102292900  4.937310e+03  8.233986e+04
11    0102294100  1.780784e+05  5.207597e+05
12    0102294900  2.108410e+03  1.080357e+06
13    0102295900  4.422250e+03  7.676963e+05
14    0102296100           NaN  2.352305e+05
15    0102296900  6.074660e+03  5.467858e+05
16    0102299100           NaN  7.060270e+05
17    0102299900  1.312680e+03  2.861603e+05
18    0102310000           NaN  5.826176e+05
19    0102391000  3.399410e+05           NaN
20    0102399000  6.957196e+04           NaN
21    0102902000           NaN  7.825017e+05
22    0102909100           NaN  1.582783e+04
23    0102909900  1.975854e+06  1.254246e+06
24    0103100000  1.312278e+07  3.897988e+05
25    0103921100           NaN  1.944600e+02
26    0103921900           NaN  7.738644e+06
27    0103929000           NaN  6.391749e+04
28    0104101000  2.609052e+06  1.749067e+05
29    0104103000           NaN  1.082540e+06
30    0104108000  2.294294e+05  1.158756e+06
31    0104201000  4.817888e+06           NaN
32    0104209000  2.259038e+05  6.169836e+04
33    0105111100  6.503631e+06  1.077335e+07
34    0105111900  1.026110e+07  1.712266e+06
35    0105119100  8.052945e+05  8.181873e+05
36    0105119900  1.272269e+05  1.489819e+06
37    0105120000  5.642664e+06  4.520214e+05
38    0105130000  1.409440e+06  1.146728e+04
39    0105140000           NaN  1.673807e+05
40    0105150000  2.380315e+04           NaN
41    0105940000           NaN  7.212885e+04
42    0105992000           NaN  1.907290e+03
43    0106110090  8.779308e+04  6.718529e+04
44    0106120090  5.126177e+04  1.710080e+06
45    0106130090  8.094779e+04  3.614400e+03
46    0106141010           NaN  4.046330e+03
47    0106141090  6.019966e+05  5.293373e+04
48    0106149090  9.940400e+02           NaN
49    0106190010  6.377409e+05  1.738984e+04

In [46]:
df2['Saldo'] = df2['ЭК'] - df2['ИМ']

In [47]:
df2 = df2.sort_values(by='Saldo', ascending = True)

In [48]:
df2.head(50)

napr        tnved            ИМ            ЭК         Saldo
9237   8517120000  7.745136e+09  2.302293e+08 -7.514907e+09
3518   3004900002  6.099597e+09  5.556704e+08 -5.543926e+09
8752   8471300000  3.327306e+09  5.234277e+07 -3.274964e+09
10118  8901201000  3.788044e+09  9.648069e+08 -2.823237e+09
9965   8708299009  2.289644e+09  1.018272e+08 -2.187817e+09
2846   2818200000  1.826741e+09  1.212022e+06 -1.825529e+09
9953   8707109000  1.855955e+09  2.048660e+08 -1.651089e+09
8755   8471500000  1.800392e+09  1.949835e+08 -1.605408e+09
9840   8703331990  1.543505e+09  3.922003e+07 -1.504285e+09
9974   8708405009  1.495371e+09  3.673759e+07 -1.458633e+09
3475   3002150000  1.497263e+09  8.179143e+07 -1.415472e+09
8146   8419600000  1.297424e+09  2.893297e+06 -1.294531e+09
3521   3004900009  1.238976e+09  2.311455e+07 -1.215862e+09
9456   8529909209  1.189690e+09  1.007785e+07 -1.179612e+09
9245   8517620009  1.219844e+09  9.567497e+07 -1.124169e+09
9811   8703231981  1.410633e+09  3.093599e+08 -1.101273e+09
10042  8708999709  1.250644e+09  1.751943e+08 -1.075449e+09
1497   1511909908  1.077010e+09  7.206635e+06 -1.069804e+09
1046   0803901000  1.075812e+09  4.537787e+07 -1.030434e+09
8849   8479899708  1.122028e+09  1.204223e+08 -1.001605e+09
4214   3926909709  1.127633e+09  1.267411e+08 -1.000892e+09
9244   8517620003  1.013326e+09  4.890836e+07 -9.644180e+08
8152   8419899890  9.843537e+08  4.491175e+07 -9.394420e+08
9914   8704239108  1.032533e+09  1.013549e+08 -9.311780e+08
9737   8701201013  9.259143e+08  4.540665e+07 -8.805076e+08
8779   8473302008  9.020946e+08  2.660664e+07 -8.754879e+08
7882   8407349908  1.012388e+09  1.475134e+08 -8.648748e+08
1365   1201900000  1.259028e+09  4.026767e+08 -8.563509e+08
8303   8429521009  9.165151e+08  8.321673e+07 -8.332984e+08
3677   3304990000  9.645676e+08  1.927395e+08 -7.718281e+08
6229   6404199000  8.235927e+08  5.585626e+07 -7.677364e+08
3476   3002190000  7.976344e+08  3.019290e+07 -7.674415e+08
9827   8703241098  8.515277e+08  9.399921e+07 -7.575285e+08
9804   8703221099  8.353863e+08  9.732082e+07 -7.380655e+08
802    0406909909  7.559752e+08  2.126499e+07 -7.347102e+08
9834   8703321990  6.854999e+08  2.728987e+07 -6.582100e+08
9420   8528599009  6.695899e+08  2.120705e+07 -6.483828e+08
7371   7326909807  8.416528e+08  2.080882e+08 -6.335646e+08
9968   8708309109  6.538368e+08  3.679134e+07 -6.170455e+08
7372   7401000000  5.989232e+08  2.428812e+06 -5.964944e+08
8144   8419400009  6.051089e+08  9.114303e+06 -5.959946e+08
8760   8471705000  6.045588e+08  1.424749e+07 -5.903113e+08
10006  8708809909  6.242601e+08  3.776180e+07 -5.864983e+08
10276  9018908409  6.087415e+08  3.089612e+07 -5.778454e+08
9175   8512200009  6.023834e+08  3.331910e+07 -5.690643e+08
3400   2934999000  5.702949e+08  3.744434e+06 -5.665505e+08
5813   6109100000  5.878965e+08  3.044029e+07 -5.574562e+08
4281   4011800000  6.129088e+08  5.823862e+07 -5.546701e+08
9267   8518309500  5.767646e+08  2.852586e+07 -5.482387e+08
9621   8542319010  5.319370e+08  8.690822e+06 -5.232462e+08

In [49]:
df2.to_csv('dataframe_saldo.csv')

In [50]:
tnvd_names = pd.read_csv('tnvd_names_395_big-saldo.csv', sep = ',')

In [51]:
tnvd_names.head(10)

,Unnamed: 0,uin,tnved,name,desc,node
0,0,5001,8517120000,телефонные аппараты,телефонные аппараты для сотовых сетей связи ил...,0
1,0,5002,3004900002,ЛЕКАРСТВЕННЫЕ СРЕДСТВА,"ЛЕКАРСТВЕННЫЕ СРЕДСТВА, ПРОЧИЕ, РАСФАСОВАННЫЕ ...",0
2,0,5003,8471300000,машины вычислительные портативные,машины вычислительные портативные массой не бо...,0
3,0,5004,8901201000,морские,"Танкеры для перевозки нефти, нефтепродуктов, х...",0
4,0,5005,8708299009,прочие,"Ремни безопасности, подушки безопасности, их ч...",0
5,0,5006,2818200000,оксид алюминия,"Оксид алюминия (глинозем), кроме искусственног...",0
6,0,5007,8707109000,прочие,Кузова для автотранспортных средств,0
7,0,5008,8471500000,блоки обработки данных,"блоки обработки данных, отличные от описанных ...",0
8,0,5009,8703331990,прочие,Средства транспортные с поршневым двигателем в...,0
9,0,5010,8708405009,коробки передач,коробки передач прочие,0

In [56]:
tnvd_names['tnved'] = tnvd_names['tnved'].astype(str)

In [57]:
tnvd_with_names = pd.merge(df2, tnvd_names, how = 'left', on = 'tnved')

tnvd_with_names.head(10)

,tnved,ИМ,ЭК,Saldo,Unnamed: 0,uin,name,desc,node
0,8517120000,7.745136e+09,2.302293e+08,-7.514907e+09,0.0,5001.0,телефонные аппараты,телефонные аппараты для сотовых сетей связи ил...,0.0
1,3004900002,6.099597e+09,5.556704e+08,-5.543926e+09,0.0,5002.0,ЛЕКАРСТВЕННЫЕ СРЕДСТВА,"ЛЕКАРСТВЕННЫЕ СРЕДСТВА, ПРОЧИЕ, РАСФАСОВАННЫЕ ...",0.0
2,8471300000,3.327306e+09,5.234277e+07,-3.274964e+09,0.0,5003.0,машины вычислительные портативные,машины вычислительные портативные массой не бо...,0.0
3,8901201000,3.788044e+09,9.648069e+08,-2.823237e+09,0.0,5004.0,морские,"Танкеры для перевозки нефти, нефтепродуктов, х...",0.0
4,8708299009,2.289644e+09,1.018272e+08,-2.187817e+09,0.0,5005.0,прочие,"Ремни безопасности, подушки безопасности, их ч...",0.0
5,2818200000,1.826741e+09,1.212022e+06,-1.825529e+09,0.0,5006.0,оксид алюминия,"Оксид алюминия (глинозем), кроме искусственног...",0.0
6,8707109000,1.855955e+09,2.048660e+08,-1.651089e+09,0.0,5007.0,прочие,Кузова для автотранспортных средств,0.0
7,8471500000,1.800392e+09,1.949835e+08,-1.605408e+09,0.0,5008.0,блоки обработки данных,"блоки обработки данных, отличные от описанных ...",0.0
8,8703331990,1.543505e+09,3.922003e+07,-1.504285e+09,0.0,5009.0,прочие,Средства транспортные с поршневым двигателем в...,0.0
9,8708405009,1.495371e+09,3.673759e+07,-1.458633e+09,0.0,5010.0,коробки передач,коробки передач прочие,0.0

In [58]:
tnvd_with_names_final = tnvd_with_names[['tnved', 'ИМ', 'ЭК', 'Saldo', 'name', 'desc']]

In [59]:
tnvd_with_names_final.head()

,tnved,ИМ,ЭК,Saldo,name,desc
0,8517120000,7.745136e+09,2.302293e+08,-7.514907e+09,телефонные аппараты,телефонные аппараты для сотовых сетей связи ил...
1,3004900002,6.099597e+09,5.556704e+08,-5.543926e+09,ЛЕКАРСТВЕННЫЕ СРЕДСТВА,"ЛЕКАРСТВЕННЫЕ СРЕДСТВА, ПРОЧИЕ, РАСФАСОВАННЫЕ ..."
2,8471300000,3.327306e+09,5.234277e+07,-3.274964e+09,машины вычислительные портативные,машины вычислительные портативные массой не бо...
3,8901201000,3.788044e+09,9.648069e+08,-2.823237e+09,морские,"Танкеры для перевозки нефти, нефтепродуктов, х..."
4,8708299009,2.289644e+09,1.018272e+08,-2.187817e+09,прочие,"Ремни безопасности, подушки безопасности, их ч..."